### ISSUE TITLE
Homebrew Error: Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by jvendetti** [msalvadores/homebrew-fourstore#2]
@msalvadores - Many homebrew commands (e.g., brew outdated, brew info) now fail with the following error:

```
➜  ~ brew info fourstore-ncbo
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/msalvadores/homebrew-fourstore/Formula/fourstore-ncbo.rb:13:in `<class:FourstoreNcbo>'
Please report this to the msalvadores/fourstore tap!
```

Use of SHA-1 ([in this line](https://github.com/msalvadores/homebrew-fourstore/blob/master/Formula/fourstore-ncbo.rb#L11) of the Formula file) is now disabled.

I found an explanation of how to update the Formula to SHA-256 in [in this issue comment](https://github.com/Homebrew/homebrew-core/issues/7058#issuecomment-261666196).  I had planned to fork your repository, commit a fix, and issue a pull request.  However, when I tried to run the curl command, it fails because the 4store.org site is gone:

```
➜  ~ curl http://4store.org/download/4store-v1.1.5.tar.gz
curl: (6) Could not resolve host: 4store.org
```

Do you have any suggestions on what to do here?  Now that 4store.org is gone, it's unclear to me how to fix your Formula file.

**Comment by msalvadores** [comment]
I would probably try to get it from https://github.com/garlik/4store/releases which is now the canonical source. I would stick to 1.1.5, I remember issues with some ontologies using 1.1.6

**Comment by jvendetti** [comment]
Thanks for the pointer @msalvadores, and for accepting the [pull request](https://github.com/msalvadores/homebrew-fourstore/pull/3).
